behaviors:
  PenguinLearning:
    trainer_type: ppo
    hyperparameters:
      # hyperparameters common to PPO and SAC
      batch_size: 128
      buffer_size: 2048
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      
      # PPO-specific hyperparameters
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 256
      num_layers: 2
      memory:
        sequence_length: 64
        memory_size: 128

    # Trainer configurations common to all trainers
    max_steps: 4.0e5
    time_horizon: 128
    summary_freq: 5000

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

environment_parameters:
  fish_speed:
    curriculum: 
      - name: Lesson0
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: -0.1
      - name: Lesson1
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 0.7
      - name: Lesson2
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 1.7
      - name: Lesson3
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 1.7
      - name: Lesson4
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 1.7
      - name: Lesson5
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 2.7
      - name: Lesson6
        value: 0.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 2.7
      - name: Lesson7
        value: 0.5
  feed_radius:
    curriculum: 
      - name: Lesson0
        value: 6.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: -0.1
      - name: Lesson1
        value: 5.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 0.7
      - name: Lesson2
        value: 4.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 1.7
      - name: Lesson3
        value: 3.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 1.7
      - name: Lesson4
        value: 2.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 1.7
      - name: Lesson5
        value: 1.0
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 2.7
      - name: Lesson6
        value: 0.5
        completion_criteria:
          measure: reward
          behavior: PenguinLearning
          signal_smoothing: true
          min_lesson_length: 80
          threshold: 2.7
      - name: Lesson7
        value: 0.2