behaviors:
  PenguinLearning:
    trainer_type: ppo
    hyperparameters:
      # hyperparameters common to PPO and SAC
      batch_size: 128
      buffer_size: 2048
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      
      # PPO-specific hyperparameters
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 256
      num_layers: 2
      memory:
        sequence_length: 64
        memory_size: 128

    # Trainer configurations common to all trainers
    max_steps: 4.0e5
    time_horizon: 128
    summary_freq: 5000

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99

curriculum:
  PenguinLearning:
    measure: reward
    thresholds: [-0.1, 0.7, 1.7, 1.7, 1.7, 2.7, 2.7]
    min_lesson_length: 80
    signal_smoothing: true
    parameters:
      fish_speed: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5]
      feed_radius: [6.0, 5.0, 4.0, 3.0, 2.0, 1.0, 0.5, 0.2]
